name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./parser
        file: ./parser/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_LOGIN }}/smart-news:latest

    - name: Install Yandex Cloud CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
        source ~/.bashrc
        yc --version  # Проверка установки

    - name: Configure Yandex Cloud CLI
      run: |
        echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
        yc config set service-account-key key.json

    - name: Configure Docker for Yandex Cloud
      run: yc container registry configure-docker

    - name: Push to Yandex Cloud Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_LOGIN }}/smart-news:latest cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY }}/smartnews:latest
        docker push cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY }}/smartnews:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install Yandex Cloud CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
        source ~/.bashrc
        yc --version  # Проверка установки

    - name: Configure Yandex Cloud CLI
      run: |
        echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
        yc config set service-account-key key.json

    - name: Configure Docker for Yandex Cloud
      run: yc container registry configure-docker

    - name: Deploy to Yandex Cloud
      run: |
        yc serverless container revision deploy \
          --container-name smartnews \
          --image cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY }}/smartnews:latest \
          --memory 512M \
          --cores 1 \
          --execution-timeout 15m \
          --concurrency 1 \
          --environment CLICKHOUSE_HOST=${{ secrets.CLICKHOUSE_HOST }} \
                        CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }} \
                        CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }} \
                        CLICKHOUSE_PORT=${{ secrets.CLICKHOUSE_PORT }} \
                        CLICKHOUSE_DB_NAME=${{ secrets.CLICKHOUSE_DB_NAME }} \
                        CLICKHOUSE_TABLE_NAME=${{ secrets.CLICKHOUSE_TABLE_NAME }}
