name: Web App Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_LOGIN }}/webapp:latest

    - name: Deploy to Yandex Cloud
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.VM_IP }} 'docker pull ${{ secrets.DOCKER_LOGIN }}/webapp:latest && docker stop webapp || true && docker rm webapp || true && docker run -d -p 80:5000 --name webapp -e FLASK_KEY=${{ secrets.FLASK_KEY }} -e MAIL_USER=${{ secrets.MAIL_USER }} -e MAIL_PWD=${{ secrets.MAIL_PWD }} -e AUTH_KEY_HASH=${{ secrets.AUTH_KEY_HASH }}  -e  CLICKHOUSE_HOST=${{ secrets.CLICKHOUSE_HOST }} -e CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }} -e CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }} -e CLICKHOUSE_PORT=${{ secrets.CLICKHOUSE_PORT }} -e CLICKHOUSE_DB_NAME=${{ secrets.CLICKHOUSE_DB_NAME }} -e CLICKHOUSE_TABLE_NAME=${{ secrets.CLICKHOUSE_TABLE_NAME }} -e FOLDER_ID=${{ secrets.FOLDER_ID }} -e API_KEY=${{ secrets.API_KEY }} ${{ secrets.DOCKER_LOGIN }}/webapp:latest'
