name: Web App Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_LOGIN }}/webapp:latest

    - name: Deploy to Yandex Cloud
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.VM_IP }} 'docker pull ${{ secrets.DOCKER_LOGIN }}/webapp:latest && docker stop webapp || true && docker rm webapp || true && docker run -d -p 80:5000 --name webapp -e FLASK_KEY=${{ secrets.FLASK_KEY }} -e API_KEY=${{ secrets.API_KEY }} -e AUTH_KEY_HASH=${{ secrets.AUTH_KEY_HASH }} ${{ secrets.DOCKER_LOGIN }}/webapp:latest'
