name: Deploy Web App to Yandex Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Transfer files
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" . user@your-vm-ip:/path/to/remote/app

    - name: Install Python dependencies
      run: |
        ssh -o StrictHostKeyChecking=no user@your-vm-ip 'cd /path/to/remote/app && pip3 install -r requirements.txt'

    - name: Restart Gunicorn
      run: |
        ssh -o StrictHostKeyChecking=no user@your-vm-ip 'sudo systemctl restart yourapp'

    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no user@your-vm-ip 'sudo systemctl restart nginx'
